server:
  port: 8090

spring:
  rabbitmq:
    host: 192.168.56.110
    port: 5672
    username: admin
    password: admin
    virtual-host: /test
    listener:
      simple:
        acknowledge-mode: manual
      direct:
        acknowledge-mode: manual
